// Generated by CoffeeScript 1.7.1
(function() {
  ***REMOVED***{
  ***REMOVED*** {
  ***REMOVED*** || 'amqp://L6Pr-jcX:DE4CaVsraUHVzH1pdFGWiO7o0ns8WcU_@black-vilthuril-36.bigwig.lshift.net:10000/tGtdT4ExyWi4',
  ***REMOVED***,
  ***REMOVED***
    },
  ***REMOVED*** {
  ***REMOVED***,
  ***REMOVED***|| "AKIAIYMT6B27XYCQDQ3Q",
  ***REMOVED***|| "+B0EH1Bfn0Yyc3vOdFbejeNK87FmZjN9zf3w47d9"
    },
  ***REMOVED*** {
  ***REMOVED***,
  ***REMOVED***,
  ***REMOVED***
    }
  };

}).call(this);
