// Generated by CoffeeScript 1.7.1
(function() {
  ***REMOVED***{
  ***REMOVED*** {
  ***REMOVED***,
  ***REMOVED***,
  ***REMOVED***,
  ***REMOVED***
    },
  ***REMOVED*** {
  ***REMOVED***,
      access_key_id: process.env.AWSAccessKeyId,
      secret_access_key: process.env.AWSSecretKey
    },
  ***REMOVED*** {
  ***REMOVED***,
  ***REMOVED***,
  ***REMOVED***
    }
  };

}).call(this);
